In [ ]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np  # Agrega la importación de NumPy
import cv2 as cv
import cvlib

# Nuevo Dataset

In [ ]:
import os
import cv2
import numpy as np

# Directorio raíz que contiene las carpetas con imágenes
directorio_raiz = "./placas/CNN letter Dataset"  # Reemplaza con la ruta de tu directorio raíz

imagenes = []  # Lista para almacenar las imágenes
etiquetas = []  # Lista para almacenar las etiquetas

# Recorre las carpetas en el directorio raíz
for carpeta in os.listdir(directorio_raiz):
    carpeta_path = os.path.join(directorio_raiz, carpeta)
    
    # Verifica si el elemento en el directorio es una carpeta
    if os.path.isdir(carpeta_path):
        # Recorre las imágenes en la carpeta
        for imagen_nombre in os.listdir(carpeta_path):
            imagen_path = os.path.join(carpeta_path, imagen_nombre)
            
            # Utiliza OpenCV para cargar la imagen
            imagen = cv2.imread(imagen_path, cv2.IMREAD_GRAYSCALE)  # Convierte la imagen a escala de grises
            if imagen is not None:
                # Agrega la imagen a la lista de imágenes
                # nuevo_tamano = (100, 100)  # Cambia estos valores al tamaño deseado
                # imagen_redimensionada = cv2.resize(imagen, nuevo_tamano)
                imagenes.append(imagen)
                # Agrega el nombre de la carpeta como etiqueta
                etiquetas.append(carpeta)

# Convierte las listas en matrices NumPy para su uso con bibliotecas de aprendizaje automático
imagenes_finales = np.array(imagenes)
targets_finales = np.array(etiquetas)

# # Aplana las matrices 3D en matrices 2D
images2 = imagenes_finales.reshape((len(imagenes_finales), -1))

# etiquetas_dict = {}
# for idx, carpeta in enumerate(os.listdir(directorio_raiz)):
#     etiquetas_dict[carpeta] = idx

# # # Mapea los nombres de las carpetas a etiquetas numéricas en la lista 'etiquetas'
# targets_2 = np.array([etiquetas_dict[carpeta] for carpeta in etiquetas])

# X_train, X_test, y_train, y_test = train_test_split(imagenes, targets_2, test_size=0.2)
# model = XGBClassifier()
# model.fit(X_train, y_train)
# y_pred = model.predict(X_test)
# accuracy = accuracy_score(y_test, y_pred)
# print("Accuracy: %.2f%%" % (accuracy * 100.0))
# from sklearn.metrics import confusion_matrix
# confusion = confusion_matrix(y_test, y_pred)
# print('Confusion Matrix\n')
# print(confusion)


In [ ]:
etiquetas_dict = {}
for idx, carpeta in enumerate(os.listdir(directorio_raiz)):
    etiquetas_dict[carpeta] = idx

# # Mapea los nombres de las carpetas a etiquetas numéricas en la lista 'etiquetas'
targets_2 = np.array([etiquetas_dict[carpeta] for carpeta in etiquetas])

In [ ]:
imagenes_finales_2d = imagenes_finales.reshape(imagenes_finales.shape[0], -1)
X_train, X_test, y_train, y_test = train_test_split(imagenes_finales_2d, targets_2, test_size=0.2)
model = XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n')
print(confusion)

In [ ]:
from joblib import dump
dump(example, 'example.joblib') 

In [ ]:
def number2char(num):
    if(num == 0):
        return 0
    elif(num == 1):
        return 1
    elif(num == 2):
        return 2
    elif(num == 3):
        return 3
    elif(num == 4):
        return 4
    elif(num == 5):
        return 5
    elif(num == 6):
        return 6
    elif(num == 7):
        return 7
    elif(num == 8):
        return 8
    elif(num == 9):
        return 9
    elif(num == 10):
        return 'A'
    elif(num == 11):
        return 'B'
    elif(num == 12):
        return 'C'
    elif(num == 13):
        return 'D'
    elif(num == 14):
        return 'E'
    elif(num == 15):
        return 'F'
    elif(num == 16):
        return 'G'
    elif(num == 17):
        return 'H'
    elif(num == 18):
        return 'I'
    elif(num == 19):
        return 'J'
    elif(num == 20):
        return 'K'
    elif(num == 21):
        return 'L'
    elif(num == 22):
        return 'M'
    elif(num == 23):
        return 'N'
    elif(num == 24):
        return 'P'
    elif(num == 25):
        return 'Q'
    elif(num == 26):
        return 'R'
    elif(num == 27):
        return 'S'
    elif(num == 28):
        return 'T'
    elif(num == 29):
        return 'U'
    elif(num == 30):
        return 'V'
    elif(num == 31):
        return 'W'
    elif(num == 32):
        return 'X'
    elif(num == 33):
        return 'Y'
    elif(num == 34):
        return 'Z'

In [ ]:
from joblib import load
model = load('modelo_final.joblib')

In [ ]:
filename = 'imagen7.png'
img = cv.imread(filename,cv.IMREAD_GRAYSCALE) 
thresh_val = 100
print(np.mean(img))
if(np.mean(img) > thresh_val):
    binarized = cv.adaptiveThreshold(img, 255,cv.ADAPTIVE_THRESH_GAUSSIAN_C, cv.THRESH_BINARY,127,5)
else:
    binarized = 255 -cv.adaptiveThreshold(img, 255,cv.ADAPTIVE_THRESH_GAUSSIAN_C, cv.THRESH_BINARY,23,-2)
# imgbin = cv.adaptiveThreshold(img, 255,cv.ADAPTIVE_THRESH_GAUSSIAN_C, cv.THRESH_BINARY,127,5)
nuevo_tamano = (75, 100)  # Cambia estos valores al tamaño deseado
imagen_redimensionada = cv.resize(binarized, nuevo_tamano)
cvlib.imgview(imagen_redimensionada, axis=True)

In [ ]:
prediccion = model.predict(imagen_redimensionada.reshape(1, -1))

# 'prediccion' ahora contiene la etiqueta predicha para la imagen.
print("Predicción:", number2char(prediccion[0]))

# otra forma

In [1]:
import numpy as np
import cv2 as cv
import pickle
import os
import cvlib

c:\Users\p1jav\miniforge3\envs\ml\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\p1jav\miniforge3\envs\ml\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\p1jav\miniforge3\envs\ml\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [6]:
x = []
y = []

In [2]:
folder = './placas/CNN letter Dataset/'
sub_folders = [name for name in os.listdir(folder) if os.path.isdir(os.path.join(folder, name))]

In [5]:
sub_folders

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

In [8]:
for i in sub_folders:
    dir_path = folder + "/" + i

    for file_path in os.listdir(dir_path):
        if os.path.isfile(os.path.join(dir_path, file_path)):
            image_path = dir_path + "/" + file_path
            if("desktop" not in image_path.lower()):
                image = cv.imread(image_path,cv.IMREAD_GRAYSCALE)
                binarized = cv.adaptiveThreshold(image, 255,cv.ADAPTIVE_THRESH_GAUSSIAN_C, cv.THRESH_BINARY,127,5)
                image_2d = binarized.flatten()
                x.append(image_2d)
                y.append(i)
            else:
                print(image_path)

./placas/CNN letter Dataset//1/desktop.ini
./placas/CNN letter Dataset//2/desktop.ini
./placas/CNN letter Dataset//3/desktop.ini
./placas/CNN letter Dataset//4/desktop.ini
./placas/CNN letter Dataset//5/desktop.ini
./placas/CNN letter Dataset//6/desktop.ini
./placas/CNN letter Dataset//7/desktop.ini
./placas/CNN letter Dataset//8/desktop.ini
./placas/CNN letter Dataset//9/desktop.ini
./placas/CNN letter Dataset//A/desktop.ini
./placas/CNN letter Dataset//B/desktop.ini
./placas/CNN letter Dataset//C/desktop.ini
./placas/CNN letter Dataset//D/desktop.ini
./placas/CNN letter Dataset//E/desktop.ini
./placas/CNN letter Dataset//F/desktop.ini
./placas/CNN letter Dataset//G/desktop.ini
./placas/CNN letter Dataset//H/desktop.ini
./placas/CNN letter Dataset//I/desktop.ini
./placas/CNN letter Dataset//J/desktop.ini
./placas/CNN letter Dataset//K/desktop.ini
./placas/CNN letter Dataset//L/desktop.ini
./placas/CNN letter Dataset//M/desktop.ini
./placas/CNN letter Dataset//N/desktop.ini
./placas/CN

In [9]:
etiquetas_dict = {}
for idx, carpeta in enumerate(os.listdir(folder)):
    etiquetas_dict[carpeta] = idx

# # Mapea los nombres de las carpetas a etiquetas numéricas en la lista 'etiquetas'
targets_2 = np.array([etiquetas_dict[carpeta] for carpeta in y])

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import xgboost as xgb
X_train, X_test, y_train, y_test = train_test_split(x, targets_2, test_size=0.3, random_state=100, stratify=y)
model = xgb.XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n')
print(confusion)

Accuracy: 98.97%
Confusion Matrix

[[303   0   0 ...   0   0   0]
 [  0 302   0 ...   0   0   0]
 [  0   1 304 ...   0   0   0]
 ...
 [  0   0   0 ... 298   5   0]
 [  0   0   0 ...   0 302   0]
 [  0   0   0 ...   0   0 242]]


In [11]:
from joblib import dump
dump(model, 'modelo_imagen_procesada.joblib') 

['modelo_imagen_procesada.joblib']